import type { Opportunity, Product, ActionLog, UserProfile } from './types'

export const mockUser: UserProfile = {
  id: 'u1',
  name: '张明',
  avatar: undefined,
  role: '销售经理',
  company: 'Bantu Immigration',
}

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-001',
    customerId: 'c1',
    customer: {
      id: 'c1',
      name: '李伟',
      passportNo: 'E12345678',
      phone: '13812345678',
      email: 'liwei@example.com',
      wechat: 'liwei_wx',
    },
    stageId: 'P1',
    serviceType: 'VISA',
    serviceTypeLabel: '旅游签证',
    estimatedAmount: 15000,
    currency: 'CNY',
    requirements: '需要办理美国旅游签证，计划8月份出行',
    destination: '美国',
    travelDate: '2024-08-15',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-16T14:30:00Z',
  },
  {
    id: 'opp-002',
    customerId: 'c2',
    customer: {
      id: 'c2',
      name: '王芳',
      passportNo: 'E23456789',
      phone: '13987654321',
      email: 'wangfang@example.com',
    },
    stageId: 'P2',
    serviceType: 'IMMIGRATION',
    serviceTypeLabel: '技术移民',
    estimatedAmount: 280000,
    currency: 'CNY',
    requirements: '加拿大联邦技术移民，IT背景',
    destination: '加拿大',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
  },
  {
    id: 'opp-003',
    customerId: 'c3',
    customer: {
      id: 'c3',
      name: '陈强',
      passportNo: 'E34567890',
      phone: '13611112222',
      email: 'chenqiang@example.com',
      wechat: 'cq_2024',
    },
    stageId: 'P3',
    serviceType: 'STUDY',
    serviceTypeLabel: '留学申请',
    estimatedAmount: 95000,
    currency: 'CNY',
    requirements: '英国硕士留学，商科方向',
    destination: '英国',
    createdAt: '2024-01-05T08:00:00Z',
    updatedAt: '2024-01-19T16:00:00Z',
  },
  {
    id: 'opp-004',
    customerId: 'c4',
    customer: {
      id: 'c4',
      name: '刘洋',
      passportNo: 'E45678901',
      phone: '13722223333',
      email: 'liuyang@example.com',
    },
    stageId: 'P1',
    serviceType: 'WORK',
    serviceTypeLabel: '工作签证',
    estimatedAmount: 45000,
    currency: 'CNY',
    requirements: '澳大利亚工作签证，厨师职位',
    destination: '澳大利亚',
    createdAt: '2024-01-18T13:00:00Z',
    updatedAt: '2024-01-18T13:00:00Z',
  },
  {
    id: 'opp-005',
    customerId: 'c5',
    customer: {
      id: 'c5',
      name: '赵敏',
      passportNo: 'E56789012',
      phone: '13833334444',
      email: 'zhaomin@example.com',
      wechat: 'zm_travel',
    },
    stageId: 'P2',
    serviceType: 'VISA',
    serviceTypeLabel: '商务签证',
    estimatedAmount: 8500,
    currency: 'CNY',
    destination: '德国',
    createdAt: '2024-01-12T09:30:00Z',
    updatedAt: '2024-01-17T10:45:00Z',
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: '美国B1/B2签证代办',
    category: '签证服务',
    price: 2500,
    currency: 'CNY',
    description: '包含材料准备、预约、面签辅导',
  },
  {
    id: 'prod-002',
    name: '加拿大EE技术移民全包',
    category: '移民服务',
    price: 180000,
    currency: 'CNY',
    description: '包含评估、文案、递交、登陆指导',
  },
  {
    id: 'prod-003',
    name: '英国硕士申请服务',
    category: '留学服务',
    price: 35000,
    currency: 'CNY',
    description: '最多申请8所学校',
  },
  {
    id: 'prod-004',
    name: '澳洲482工作签证',
    category: '工作签证',
    price: 28000,
    currency: 'CNY',
    description: '雇主担保类工作签证',
  },
  {
    id: 'prod-005',
    name: '申根商务签证',
    category: '签证服务',
    price: 1800,
    currency: 'CNY',
    description: '多次往返商务签证',
  },
  {
    id: 'prod-006',
    name: '翻译公证服务',
    category: '增值服务',
    price: 500,
    currency: 'CNY',
    description: '每份文件翻译及公证',
  },
  {
    id: 'prod-007',
    name: '加急处理费',
    category: '增值服务',
    price: 2000,
    currency: 'CNY',
    description: '优先处理通道',
  },
]

export const mockActionLogs: Record<string, ActionLog[]> = {
  'opp-001': [
    {
      id: 'log-001',
      opportunityId: 'opp-001',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'FORM',
      actionLabel: '创建商机',
      timestamp: '2024-01-15T09:00:00Z',
      remark: '客户咨询美签',
    },
    {
      id: 'log-002',
      opportunityId: 'opp-001',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'NOTE',
      actionLabel: '添加备注',
      timestamp: '2024-01-16T14:30:00Z',
      remark: '已确认8月出行计划',
    },
  ],
  'opp-002': [
    {
      id: 'log-003',
      opportunityId: 'opp-002',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'FORM',
      actionLabel: '创建商机',
      timestamp: '2024-01-10T10:00:00Z',
    },
    {
      id: 'log-004',
      opportunityId: 'opp-002',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至P2',
      timestamp: '2024-01-15T11:00:00Z',
      remark: '需求确认完成',
    },
    {
      id: 'log-005',
      opportunityId: 'opp-002',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'MATCH',
      actionLabel: '匹配产品',
      timestamp: '2024-01-18T11:00:00Z',
      remark: '推荐EE全包方案',
    },
  ],
  'opp-003': [
    {
      id: 'log-006',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'FORM',
      actionLabel: '创建商机',
      timestamp: '2024-01-05T08:00:00Z',
    },
    {
      id: 'log-007',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至P2',
      timestamp: '2024-01-08T09:00:00Z',
    },
    {
      id: 'log-008',
      opportunityId: 'opp-003',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'MATCH',
      actionLabel: '匹配产品',
      timestamp: '2024-01-12T14:00:00Z',
    },
    {
      id: 'log-009',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至P3',
      timestamp: '2024-01-19T16:00:00Z',
      remark: '进入报价阶段',
    },
  ],
}
