import type { Opportunity, Product, ActionLog, UserProfile, Currency } from './types'

// ─── Exchange Rate (Fixed for demo) ─────────────────────────────────────────
// Value represents how many units of currency = 1 CNY
export const EXCHANGE_RATES: Record<Currency, number> = {
  CNY: 1,
  IDR: 2273, // 1 CNY ≈ 2273 IDR
}

export const mockUser: UserProfile = {
  id: 'u1',
  name: '张明',
  avatar: undefined,
  role: '销售经理',
  company: 'Bantu Immigration',
}

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-001',
    customerId: 'c1',
    customer: {
      id: 'c1',
      name: '李伟',
      passportNo: 'E12345678',
      phone: '13812345678',
      email: 'liwei@example.com',
      wechat: 'liwei_wx',
    },
    stageId: 'P1',
    status: 'active',
    serviceType: 'VISA',
    serviceTypeLabel: '旅游签证',
    estimatedAmount: 15000,
    currency: 'CNY',
    requirements: '需要办理美国旅游签证，计划8月份出行',
    destination: '美国',
    travelDate: '2024-08-15',
    assignee: '张明',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-16T14:30:00Z',
  },
  {
    id: 'opp-002',
    customerId: 'c2',
    customer: {
      id: 'c2',
      name: '王芳',
      passportNo: 'E23456789',
      phone: '13987654321',
      email: 'wangfang@example.com',
    },
    stageId: 'P2',
    status: 'active',
    serviceType: 'IMMIGRATION',
    serviceTypeLabel: '技术移民',
    estimatedAmount: 280000,
    currency: 'CNY',
    requirements: '加拿大联邦技术移民，IT背景',
    destination: '加拿大',
    assignee: '李娜',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
  },
  {
    id: 'opp-003',
    customerId: 'c3',
    customer: {
      id: 'c3',
      name: '陈强',
      passportNo: 'E34567890',
      phone: '13611112222',
      email: 'chenqiang@example.com',
      wechat: 'cq_2024',
    },
    stageId: 'P3',
    status: 'active',
    serviceType: 'STUDY',
    serviceTypeLabel: '留学申请',
    estimatedAmount: 95000,
    currency: 'CNY',
    requirements: '英国硕士留学，商科方向',
    destination: '英国',
    assignee: '张明',
    createdAt: '2024-01-05T08:00:00Z',
    updatedAt: '2024-01-19T16:00:00Z',
  },
  {
    id: 'opp-004',
    customerId: 'c4',
    customer: {
      id: 'c4',
      name: '刘洋',
      passportNo: 'E45678901',
      phone: '13722223333',
      email: 'liuyang@example.com',
    },
    stageId: 'P1',
    status: 'active',
    serviceType: 'WORK',
    serviceTypeLabel: '工作签证',
    estimatedAmount: 45000,
    currency: 'CNY',
    requirements: '澳大利亚工作签证，厨师职位',
    destination: '澳大利亚',
    assignee: '张明',
    createdAt: '2024-01-18T13:00:00Z',
    updatedAt: '2024-01-18T13:00:00Z',
  },
  {
    id: 'opp-005',
    customerId: 'c5',
    customer: {
      id: 'c5',
      name: '赵敏',
      passportNo: 'E56789012',
      phone: '13833334444',
      email: 'zhaomin@example.com',
      wechat: 'zm_travel',
    },
    stageId: 'P2',
    status: 'active',
    serviceType: 'VISA',
    serviceTypeLabel: '商务签证',
    estimatedAmount: 8500,
    currency: 'CNY',
    destination: '德国',
    assignee: '李娜',
    createdAt: '2024-01-12T09:30:00Z',
    updatedAt: '2024-01-17T10:45:00Z',
  },
  {
    id: 'opp-007',
    customerId: 'c7',
    customer: {
      id: 'c7',
      name: '周林',
      passportNo: 'G89012345',
      phone: '13955556666',
      email: 'zhoulin@example.com',
    },
    stageId: 'P4',
    status: 'active',
    serviceType: 'IMMIGRATION',
    serviceTypeLabel: '移民签证',
    estimatedAmount: 320000,
    currency: 'CNY',
    requirements: '加拿大永久居民申请',
    destination: '加拿大',
    assignee: '张明',
    p2Data: [
      {
        productId: 'prod-002',
        cycle: '12个月',
      },
      {
        productId: 'prod-006',
      },
    ],
    p3Data: [
      {
        productId: 'prod-002',
        lockedPrice: 180000,
        currency: 'CNY',
      },
      {
        productId: 'prod-006',
        lockedPrice: 500,
        currency: 'CNY',
      },
    ],
    p4Data: {
      contractStatus: 'returned',
      uploadedAt: '2024-01-22T10:30:00Z',
      notes: '合同已由客户签署并回传',
    },
    createdAt: '2024-01-10T14:00:00Z',
    updatedAt: '2024-01-22T10:30:00Z',
  },
  {
    id: 'opp-008',
    customerId: 'c8',
    customer: {
      id: 'c8',
      name: '何思',
      passportNo: 'H90123456',
      phone: '13866667777',
      email: 'hesi@example.com',
    },
    stageId: 'P5',
    status: 'active',
    serviceType: 'VISA',
    serviceTypeLabel: '工作签证',
    estimatedAmount: 42000,
    currency: 'CNY',
    destination: '新西兰',
    assignee: '李娜',
    p2Data: [
      {
        productId: 'prod-004',
        cycle: '3个月',
      },
    ],
    p3Data: [
      {
        productId: 'prod-004',
        lockedPrice: 28000,
        currency: 'CNY',
      },
    ],
    p5Data: {
      bankAccount: '4006701234567890',
      dueAmount: 42000,
      receivedAmount: 35000,
      paymentStatus: 'pending',
    },
    createdAt: '2024-01-12T15:00:00Z',
    updatedAt: '2024-01-23T14:00:00Z',
  },
  {
    id: 'opp-009',
    customerId: 'c9',
    customer: {
      id: 'c9',
      name: '吴涛',
      passportNo: 'I01234567',
      phone: '13977778888',
      email: 'wutao@example.com',
    },
    stageId: 'P6',
    status: 'active',
    serviceType: 'STUDY',
    serviceTypeLabel: '留学服务',
    estimatedAmount: 95000,
    currency: 'CNY',
    destination: '澳大利亚',
    assignee: '张明',
    p2Data: [
      {
        productId: 'prod-003',
      },
    ],
    p3Data: [
      {
        productId: 'prod-003',
        lockedPrice: 35000,
        currency: 'CNY',
      },
    ],
    p6Data: {
      materials: [
        {
          id: 'mat-001',
          name: '护照首页',
          status: 'approved',
          ocrStatus: 'completed',
          uploadedAt: '2024-01-20T11:00:00Z',
        },
        {
          id: 'mat-002',
          name: '成绩单',
          status: 'approved',
          ocrStatus: 'completed',
          uploadedAt: '2024-01-20T11:30:00Z',
        },
        {
          id: 'mat-003',
          name: '推荐信',
          status: 'pending_review',
          ocrStatus: 'pending',
          uploadedAt: '2024-01-22T09:00:00Z',
        },
        {
          id: 'mat-004',
          name: '雅思成绩',
          status: 'pending_review',
          ocrStatus: 'pending',
          uploadedAt: '2024-01-22T10:00:00Z',
        },
      ],
      lastUpdatedAt: '2024-01-22T10:00:00Z',
    },
    createdAt: '2024-01-08T16:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'opp-010',
    customerId: 'c10',
    customer: {
      id: 'c10',
      name: '傅莉',
      passportNo: 'J12345678',
      phone: '13988889999',
      email: 'fuli@example.com',
    },
    stageId: 'P7',
    status: 'active',
    serviceType: 'VISA',
    serviceTypeLabel: '旅游签证',
    estimatedAmount: 15000,
    currency: 'CNY',
    destination: '日本',
    assignee: '张明',
    p2Data: [
      {
        productId: 'prod-001',
      },
    ],
    p3Data: [
      {
        productId: 'prod-001',
        lockedPrice: 2500,
        currency: 'CNY',
      },
    ],
    p7Data: {
      progressPoints: [
        {
          id: 'pp-001',
          label: '领馆接收申请',
          status: 'completed',
          timestamp: '2024-01-15T10:00:00Z',
        },
        {
          id: 'pp-002',
          label: '正在审理',
          status: 'completed',
          timestamp: '2024-01-20T14:00:00Z',
        },
        {
          id: 'pp-003',
          label: '签证贴纸完成',
          status: 'in_progress',
        },
      ],
      deliveryStatus: 'in_transit',
    },
    createdAt: '2024-01-05T09:00:00Z',
    updatedAt: '2024-01-23T15:00:00Z',
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: '美国B1/B2签证代办',
    category: '签证服务',
    price: 2500,
    currency: 'CNY',
    description: '包含材料准备、预约、面签辅导',
    difficulty: 2,
  },
  {
    id: 'prod-002',
    name: '加拿大EE技术移民全包',
    category: '移民服务',
    price: 180000,
    currency: 'CNY',
    description: '包含评估、文案、递交、登陆指导',
    difficulty: 4,
    billingCycles: ['6个月', '12个月', '18个月'],
  },
  {
    id: 'prod-003',
    name: '英国硕士申请服务',
    category: '留学服务',
    price: 35000,
    currency: 'CNY',
    description: '最多申请8所学校',
    difficulty: 3,
    billingCycles: ['一次性'],
  },
  {
    id: 'prod-004',
    name: '澳洲482工作签证',
    category: '工作签证',
    price: 28000,
    currency: 'CNY',
    description: '雇主担保类工作签证',
    difficulty: 3,
    billingCycles: ['3个月', '6个月'],
  },
  {
    id: 'prod-005',
    name: '申根商务签证',
    category: '签证服务',
    price: 1800,
    currency: 'CNY',
    description: '多次往返商务签证',
    difficulty: 1,
  },
  {
    id: 'prod-006',
    name: '翻译公证服务',
    category: '增值服务',
    price: 500,
    currency: 'CNY',
    description: '每份文件翻译及公证',
    difficulty: 1,
  },
  {
    id: 'prod-007',
    name: '加急处理费',
    category: '增值服务',
    price: 2000,
    currency: 'CNY',
    description: '优先处理通道',
    difficulty: 1,
  },
  {
    id: 'prod-008',
    name: '葡萄牙黄金签证',
    category: '移民服务',
    price: 480000,
    currency: 'CNY',
    description: '房产投资路径，全家适用',
    difficulty: 5,
    billingCycles: ['12个月', '24个月'],
  },
]

export const mockActionLogs: Record<string, ActionLog[]> = {
  'opp-001': [
    {
      id: 'log-001',
      opportunityId: 'opp-001',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-15T09:00:00Z',
      remark: '客户咨询美签',
    },
    {
      id: 'log-002',
      opportunityId: 'opp-001',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'NOTE',
      actionLabel: '添加备注',
      timestamp: '2024-01-16T14:30:00Z',
      remark: '已确认8月出行计划',
    },
  ],
  'opp-002': [
    {
      id: 'log-003',
      opportunityId: 'opp-002',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-10T10:00:00Z',
    },
    {
      id: 'log-004',
      opportunityId: 'opp-002',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P2',
      timestamp: '2024-01-15T11:00:00Z',
      remark: '需求确认完成',
    },
    {
      id: 'log-005',
      opportunityId: 'opp-002',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'MATCH',
      actionLabel: '匹配产品',
      timestamp: '2024-01-18T11:00:00Z',
      remark: '推荐EE全包方案',
    },
  ],
  'opp-003': [
    {
      id: 'log-006',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-05T08:00:00Z',
    },
    {
      id: 'log-007',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P2',
      timestamp: '2024-01-08T09:00:00Z',
    },
    {
      id: 'log-008',
      opportunityId: 'opp-003',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'MATCH',
      actionLabel: '匹配产品',
      timestamp: '2024-01-12T14:00:00Z',
      remark: '确认英国硕士申请服务',
    },
    {
      id: 'log-009',
      opportunityId: 'opp-003',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P3',
      timestamp: '2024-01-19T16:00:00Z',
      remark: '进入报价阶段',
    },
  ],
  'opp-004': [
    {
      id: 'log-010',
      opportunityId: 'opp-004',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-18T13:00:00Z',
      remark: '客户咨询澳洲厨师工签',
    },
  ],
  'opp-005': [
    {
      id: 'log-011',
      opportunityId: 'opp-005',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-12T09:30:00Z',
    },
    {
      id: 'log-012',
      opportunityId: 'opp-005',
      operatorId: 'u2',
      operatorName: '李娜',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P2',
      timestamp: '2024-01-14T10:00:00Z',
      remark: '德国商务签证需求确认',
    },
  ],
  'opp-006': [
    {
      id: 'log-013',
      opportunityId: 'opp-006',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'CREATE',
      actionLabel: '创建商机',
      timestamp: '2024-01-02T10:00:00Z',
      remark: '客户计划投资葡萄牙黄金签证',
    },
    {
      id: 'log-014',
      opportunityId: 'opp-006',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P2',
      timestamp: '2024-01-08T11:00:00Z',
    },
    {
      id: 'log-015',
      opportunityId: 'opp-006',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'MATCH',
      actionLabel: '匹配产品',
      timestamp: '2024-01-15T14:30:00Z',
      remark: '推荐黄金签证+翻译公证组合',
    },
    {
      id: 'log-016',
      opportunityId: 'opp-006',
      operatorId: 'u1',
      operatorName: '张明',
      actionType: 'STAGE_CHANGE',
      actionLabel: '推进至 P3',
      timestamp: '2024-01-20T09:00:00Z',
      remark: '客户确认方案，进入报价',
    },
  ],
}
