version = 5.4.0
archive_dir = /etc/letsencrypt/archive/admin.oabantuqifu.com
cert = /etc/letsencrypt/live/admin.oabantuqifu.com/cert.pem
privkey = /etc/letsencrypt/live/admin.oabantuqifu.com/privkey.pem
chain = /etc/letsencrypt/live/admin.oabantuqifu.com/chain.pem
fullchain = /etc/letsencrypt/live/admin.oabantuqifu.com/fullchain.pem
[renewalparams]
account = 92860c3117fbfff586b7be5b8ac57abf
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
admin.oabantuqifu.com = /var/www/certbot
